apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: spring-petclinic  # 변경된 부분 -> petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic  # 변경된 부분 -> petclinic 
  template:
    metadata:
      labels:
        app: spring-petclinic  # 변경된 부분 -> petclinic
    spec:
      containers:
      - name: petclinic
        image: kwonhyeokjun/myjenkins-blueocean:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_URL
          value: jdbc:mysql://mysqlserver/petclinic
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: my-dockerhub-secret
      restartPolicy: Always
